### ISSUE TITLE
`test` results in unexpected token error

### ISSUE THREAD

**Issue by lorengordon** [lorengordon/ash-linux-formula#85]
Issue is in authconfig.sls. parens around the test blocks are invalid. removing the parens results in a successful test.

this is invalid:
```
test (-h /etc/pam.d/password-auth) -a (-h /etc/pam.d/system-auth)
-bash: syntax error near unexpected token `-h'
```

this is fine:
```
test -h /etc/pam.d/password-auth -a -h /etc/pam.d/system-auth
```

**Comment by ferricoxide** [comment]
That was executed by BASH? Normally, one uses notation like:
~~~
if [ -h /path/to/file1 ] && [ -h /path/to/file2 ]
~~~
Notation-style for something that will be evaluated by a Bourne-style shell. Was this previously targeted for or being evaluated by another scripting framework?

**Comment by lorengordon** [comment]
I assume bash. It was in one of the `unless` statements in authconfig.sls. Since it was in the `unless` statement, the error message was only visible if debug logging was enabled, and the error was not elevated into the output of the state run; it simply affected the logic of whether or not the state executed.

**Comment by lorengordon** [comment]
You can follow the commit reference to see the change to the code.
